# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uservoice}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Greim"]
  s.date = %q{2010-07-02}
  s.description = %q{This adds Uservoice support to your Rails application
      including single sign-on.}
  s.email = %q{alexxx@iltempo.de}
  s.extra_rdoc_files = [
    "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "generators/uservoice/USAGE",
     "generators/uservoice/templates/uservoice_template.yml",
     "generators/uservoice/uservoice_generator.rb",
     "init.rb",
     "lib/uservoice.rb",
     "lib/uservoice/instance_methods.rb",
     "lib/uservoice/token.rb",
     "lib/uservoice/view_helpers.rb",
     "test/helper.rb",
     "test/test_uservoice.rb",
     "test/test_uservoice_generator.rb",
     "test/test_uservoice_sso.rb",
     "test/test_uservoice_token.rb",
     "test/uservoice_test.yml",
     "uservoice.gemspec"
  ]
  s.homepage = %q{http://github.com/iltempo/uservoice}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Uservoice for your Rails application}
  s.test_files = [
    "test/helper.rb",
     "test/test_uservoice.rb",
     "test/test_uservoice_generator.rb",
     "test/test_uservoice_sso.rb",
     "test/test_uservoice_token.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ezcrypto>, [">= 0.7.2"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.1"])
      s.add_runtime_dependency(%q<actionpack>, [">= 2.1"])
      s.add_runtime_dependency(%q<rails>, [">= 2.1"])
    else
      s.add_dependency(%q<ezcrypto>, [">= 0.7.2"])
      s.add_dependency(%q<activesupport>, [">= 2.1"])
      s.add_dependency(%q<actionpack>, [">= 2.1"])
      s.add_dependency(%q<rails>, [">= 2.1"])
    end
  else
    s.add_dependency(%q<ezcrypto>, [">= 0.7.2"])
    s.add_dependency(%q<activesupport>, [">= 2.1"])
    s.add_dependency(%q<actionpack>, [">= 2.1"])
    s.add_dependency(%q<rails>, [">= 2.1"])
  end
end

