# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uservoice}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Greim"]
  s.date = %q{2010-01-01}
  s.description = %q{This adds Uservoice user feedback to your Rails application.
      You can set Uservoice properties in a central configuration file and override
      settings like forum id (for payed accounts) in your layout or view.}
  s.email = %q{alexxx@iltempo.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "generators/uservoice/USAGE",
     "generators/uservoice/templates/uservoice.js",
     "generators/uservoice/templates/uservoice_template.yml",
     "generators/uservoice/uservoice_generator.rb",
     "init.rb",
     "lib/uservoice.rb",
     "lib/uservoice/class_methods.rb",
     "lib/uservoice/instance_methods.rb",
     "lib/uservoice/uservoice_helper.rb",
     "test/helper.rb",
     "test/test_uservoice.rb",
     "test/test_uservoice_generator.rb",
     "test/uservoice_test.yml"
  ]
  s.homepage = %q{http://github.com/iltempo/uservoice}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Uservoice for your Rails application}
  s.test_files = [
    "test/helper.rb",
     "test/test_uservoice.rb",
     "test/test_uservoice_generator.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

